# Set default value for BUILD_VARIANT
BUILD_VARIANT ?= "debug"

DISTROOVERRIDES .= ":${BUILD_VARIANT}-variant"
DISTRO_FEATURES:append = " ${BUILD_VARIANT}-variant "

TMPDIR ?= "${TOPDIR}/tmp-${BUILD_VARIANT}"
BUILDHISTORY_DIR ?= "${TOPDIR}/buildhistory-${BUILD_VARIANT}"

IMAGE_TYPE_ID ?= "DEV"

# Drop LIBC suffix from TMPDIR
TCLIBCAPPEND = ""

# Add BUILD_VARIANT to Bitbake build configuration output
BUILDCFG_VARS:append = " BUILD_VARIANT "

#Required for unpacking ipk packages
HOSTTOOLS:append = " xz"

# To support layered ipk generation
RDK_ARTIFACTS_BASE_URL = "https://partners.artifactory.comcast.com/artifactory"
RDK_ARTIFACTS_URL = "partners.artifactory.comcast.com/artifactory"
